include:
  - template: Auto-DevOps.gitlab-ci.yml

test:dind:
  stage: test
  image: docker/compose
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:dind
  script:
    - docker-compose up --exit-code-from unittest unittest
  after_script:
    - docker-compose down -v
