version: "3.2"
services:
  unittest:
    image: node:16.0.0
    command: bash -c 'npm install && npm run test:replicaset'
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - MONGODB_HOST=mongodb-primary
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=${MONGO_PWD}
    depends_on:
      - mongodb-primary
      - mongodb-secondary
      - mongodb-arbiter
  mongodb-primary:
    image: 'bitnami/mongodb:4.4'
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=${MONGO_PWD}
      - MONGODB_REPLICA_SET_KEY=${MONGO_REPLICA_SET_KEY}
      - MONGODB_USERNAME=test
      - MONGODB_PASSWORD=${MONGO_PWD}
      - MONGODB_DATABASE=test
    volumes:
      - 'mongodb_master_data:/bitnami'
    ports:
      - "27017:27017"
  mongodb-secondary:
    image: 'bitnami/mongodb:4.4'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=${MONGO_PWD}
      - MONGODB_REPLICA_SET_KEY=${MONGO_REPLICA_SET_KEY}
      - MONGODB_USERNAME=test
      - MONGODB_PASSWORD=${MONGO_PWD}
      - MONGODB_DATABASE=test
      - ALLOW_EMPTY_PASSWORD=yes
  mongodb-arbiter:
    image: 'bitnami/mongodb:4.4'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=${MONGO_PWD}
      - MONGODB_REPLICA_SET_KEY=${MONGO_REPLICA_SET_KEY}
      - MONGODB_USERNAME=test
      - MONGODB_PASSWORD=${MONGO_PWD}
      - MONGODB_DATABASE=test
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  mongodb_master_data:
    driver: local
